import { Play } from "lucide-react";

export default function ShowcasePage() {
  const demos = [
    {
      id: 1,
      title: "Cyberpunk City",
      prompt: "A futuristic city with neon lights and flying cars, cinematic 4k",
      video: "/demo1.mp4", // This matches your file in the public folder
    },
    {
      id: 2,
      title: "Ocean Sunset",
      prompt: "Golden hour sunset over a calm ocean, photorealistic, 8k",
      video: "/demo2.mp4",
    },
    {
      id: 3,
      title: "Astronaut on Mars",
      prompt: "An astronaut walking on the red surface of Mars, high detail",
      video: "/demo3.mp4",
    },
  ];

  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-2">Community Showcase</h1>
      <p className="text-gray-400 mb-8">Best videos generated by Clivio AI users this week.</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {demos.map((demo) => (
          <div key={demo.id} className="group relative bg-zinc-900 border border-white/10 rounded-2xl overflow-hidden hover:border-blue-500/50 transition-all duration-300">
            {/* Video Player */}
            <div className="aspect-video relative">
              <video 
                src={demo.video}
                controls
                className="w-full h-full object-cover"
                poster="https://via.placeholder.com/600x400/000000/FFFFFF?text=Loading..." 
              />
            </div>

            {/* Prompt Info */}
            <div className="p-5">
              <h3 className="font-bold text-lg mb-2 text-white">{demo.title}</h3>
              <p className="text-sm text-gray-400 line-clamp-2">"{demo.prompt}"</p>
            </div>
            
            {/* Badge */}
            <div className="absolute top-3 right-3 bg-blue-600/90 backdrop-blur-md px-3 py-1 rounded-full text-xs font-bold text-white">
              Featured
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}